config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: :registrable do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'pages#home'
  resources :categories, only: [:index, :show]
  resources :items, only: [:show]

  namespace :admin do
    get '', to: 'pages#admin', as: '/'
    resources :categories
    resources :items
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items

  mount_uploader :avatar, AvatarUploader
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category

  mount_uploaders :images, ImagesUploader
  serialize :images, JSON
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
          :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @admin_category = Category.new
    respond_with(@admin_category)
  end

  def edit

  end

  def create
    @admin_category = Category.new(category_params)
    @admin_category.save
    respond_with(@admin_category)
  end

  def update
    @admin_category.update(category_params)
    respond_with(@admin_category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
  def set_category
    @admin_category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title, :avatar)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  respond_to :html

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @admin_item = Item.new
    respond_with(@admin_item)
  end

  def edit
  end

  def create
    @admin_item = Item.new(item_params)
    @admin_item.save
    respond_with(@admin_item)

  end

  def update
    @admin_item.update(item_params)
    respond_with(@admin_item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  private
  def set_item
    @admin_item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:id, :title, :description, :category_id, {images: []})
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  before_action :authenticate_user!

  def admin
  end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    @category = Category.find(params[:id])
    respond_with(@category)
  end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    @item = Item.find(params[:id])
    respond_with(@item)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/categories/_form.html.slim
= form_for [:admin, @admin_category] do |f|
  - if @admin_category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@admin_category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @admin_category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :avatar
    = f.file_field :avatar
  .actions = f.submit

app/views/admin/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'  |
= link_to 'Back', admin_categories_path

app/views/admin/categories/index.html.slim
#page-categories
  .container
    .text-center
      h1 Каталог
    - @categories.each do |category|
      .col-md-4
        - unless category.avatar.blank?
          = link_to admin_category_path(category)
            = image_tag category.avatar.url(:thumb)
            .shadow-cat
          p id='cat-title'= category.title
        - else
          = link_to category.title, admin_category_path(category)

    = link_to 'New category', new_admin_category_path, class: 'btn btn-default'

app/views/admin/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/admin/categories/show.html.slim
#categories-show
  .container
    p#notice = notice


    h1= @admin_category.title
    = link_to 'Edit', edit_admin_category_path(@admin_category)
    '  |
    = link_to 'Back', admin_categories_path
    p= image_tag @admin_category.avatar.url(:thumb) unless @admin_category.avatar.blank?

    #cat-list
      - @admin_category.items.each do |item|
        .col-md-4
          - unless item.images.blank?
            = link_to admin_item_path(item) ,method: :get do
              = image_tag item.images.first.url(:thumb)
              .shadow
              = button_to 'Подбробнее', item_path(item), method: :get, class: 'btn btn-default cat-show2 '
          - else
            = link_to item.title, admin_item_path(item)

app/views/admin/items/_form.html.slim
= form_for [:admin ,@admin_item] do |f|
  - if @admin_item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@admin_item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @admin_item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :images
    = f.file_field :images, multiple: true
  .field
    = f.label :category
    = f.collection_select( :category_id, Category.all, :id, :title)
  .actions = f.submit

app/views/admin/items/edit.html.slim
h1 Editing item

== render 'form'

= link_to 'Show', @admin_item
'  |
= link_to 'Back', admin_items_path

app/views/admin/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Title
      th Description
      th Images
      th Category
      th
      th
      th

  tbody
    - @items.each do |item|
      tr
        td = item.title
        td = item.description
        td = item.category
        td = link_to 'Show', item
        td = link_to 'Edit', edit_admin_item_path(item)
        td = link_to 'Destroy', item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Item', new_admin_item_path

app/views/admin/items/new.html.slim
.container
  h1 New item

  == render 'form'

app/views/admin/items/show.html.slim
#item-show
  .container
    p#notice = notice
    = link_to 'Edit', edit_admin_item_path(@admin_item), class: 'btn btn-primary'
    '  |
    = link_to 'Back', admin_items_path, class: 'btn btn-danger'
    p
      = @admin_item.title


    .slider-for
      - @admin_item.images.each do |image|
        = image_tag image.url(:thumb)

    .slider-nav
      - @admin_item.images.each do |image|
        = image_tag image.url(:thumb)
    p
      strong Category:
      = @admin_item.category.title

    p.item-desc
      strong Описание:
      = @admin_item.description

app/views/admin/pages/admin.html.slim
#admin-home
  .container
    = link_to 'Создать Категорию', new_admin_category_path, class: 'btn btn-primary'
    = link_to 'Создать Пост', new_admin_item_path, class: 'btn btn-success'

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'  |
= link_to 'Back', categories_path

app/views/categories/index.html.slim
#page-categories
  .container
    .text-center
      h1 Каталог
    - @categories.each do |category|
      .col-md-4
        - unless category.avatar.blank?
          = link_to category_path(category)
            = image_tag category.avatar.url(:thumb)
            .shadow-cat
          p id='cat-title'= category.title
        - else
          = link_to category.title, category_path(category)

app/views/categories/show.html.slim
#categories-show
  .container
    p#notice = notice

    h1= @category.title
    = link_to 'Back', categories_path, class: 'btn btn-default cat-show'

    #cat-list
      - @category.items.each do |item|
        .col-md-4
          - unless item.images.blank?
            = link_to item_path(item), method: :get do
              = image_tag item.images.first.url(:thumb)
              .shadow
              = button_to 'Подбробнее', item_path(item),method: :get , class: 'btn btn-default cat-show2 '
          - else
            = link_to item.title, item_path(item)

app/views/items/_form.html.slim
= form_for(@item , html: { class: 'form-horizontal', multipart: true }) do |f|
  - if @item.errors.any?
    #error_explanation
      h2 = "#{pluralize(@item.errors.count, "error")} prohibited this item from being saved:"
      ul
        - @item.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :images
    = f.file_field :images, multiple: true
  .field
    = f.label :category
    = f.collection_select( :category_id, Category.all, :id, :title)
  .actions = f.submit

app/views/items/index.html.slim
h1 Listing items

table
  thead
    tr
      th Title
      th Description
      th Images
      th Category
      th
      th
      th

  tbody
    - @items.each do |item|
      tr
        td = item.title
        td = item.description
        td = item.category
        td = link_to 'Show', item
        td = link_to 'Edit', edit_item_path(item)
        td = link_to 'Destroy', item, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Item', new_item_path

app/views/items/new.html.slim
.container
  h1 New item

  == render 'form'

  = link_to 'Back', items_path

app/views/items/show.html.slim
#item-show
  .container
    p#notice = notice

    .text-center
      h1.show-title= @item.title

    .slider-for
      - @item.images.each do |image|
        = image_tag image.url(:thumb)

    .slider-nav
      - @item.images.each do |image|
        = image_tag image.url(:thumb)

    p.item-desc
      strong Описание:
      = @item.description

app/views/layouts/_header.html.slim
#header-info
  .container
    #header-text
      a href='tel:+79964474748'
        i class='fa fa-phone'
        | 8(999)138-00-99

      a href='#'
        i class='fa fa-envelope' id='header-mail'
        | a-oleg@list.ru

      a href='#' class='header-contacts'
        i class='fa fa-vk' class='contacts'
      a href='#'
        i class='fa fa-whatsapp' class='contacts'
      a href='#'
        i class='fa fa-telegram' class='contacts'

#header-main
  .container
    - if current_user && current_user.admin?
      = link_to admin_path , method: :get
        = image_tag('secondDesignLogo.jpg')
    - else
      = link_to root_path, method: :get
        = image_tag('secondDesignLogo.jpg')

    .menu
      ul
        li
          =link_to 'Главная', root_path, method: :get
        li
          - if current_user && current_user.admin?
            =link_to 'Категории', admin_categories_path
          - else
            =link_to 'Категории', categories_path
        li
          - if current_user && current_user.admin?
            =link_to 'Выйти', destroy_user_session_path, method: :delete
          - else
            a href='#' О нас
        li
          - if current_user && current_user.admin?
            =link_to 'Создать', new_admin_item_path
          - else
            a href='#' Контакты

app/views/layouts/application.html.slim
doctype html
html
  head
    title My App
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/pages/home.html.slim
#main
  .container
    .slick-slider
      div
        img src='assets/main2.jpg'
        .info id='first'
          h1 Добро пожаловать !
          p Вызовите нашего дизайнера прямо сейчас !
          button class='slider-btn'
            a href='tel:89964474748'
            |Позвоните нам
            i class='fa fa-mobile'
      div
        img src='assets/main3black.jpg'
        .secondly-info
          h1 Мы подберем вам
          p стильный дизайн , подходящий вам по стилю , размеру
      div
        img src='assets/main4black.jpg'
        .third-info
          h1 Гарантируем
          p Качество исполнения, выдержанность сроков, профессиональный подход

    #col-bars
      div class='row centered'
        div class='col-lg-4'
          i class='fa fa-user-plus'
          h4 Индивидуальность
          p Мы не просто предлагаем готовый продукт за ваши деньги. Наши дизайнеры всегда готовы приехать, обсудить все мельчайшие детали проекта , осуществить замеры , воссоздать эскиз будущего проекта . И только после вашего одобрения, заказ будет выполнен.

        div class='col-lg-4'
          i class='fa fa-diamond'
          h4 Эксклюзивность
          p Каждый наш проект по-настоящему уникален . Вряд ли вам удастся раздобыть второе такое изделие, какое могло встретиться у нас. Все благодаря индивидуальному подходу к клиентам . Мы внимательнейшим образом изучаем все пожелания клиента и трансформируем их в изящный продукт.

        div class='col-lg-4'
          i class='fa fa-trophy'
          h4 Качество и сроки
          p Бесспорное достоинство нашего салона - безупречное качество и выдержанные сроки . Вам не придется дожидаться выполнения заказа сверх обозначенного времени, а качество работы заставит приятно изумиться. Одобрение и удовлетворенность клиентов для нас превыше всего.

  #description
    img src='assets/inside.jpg'
    #description-title
      h1 Изготовление качественной мебели на заказ с индивидуальными мерками в г. Брянске.
      p На рынке с 2010 года

    #home-about
      .container-fluid
        h1
          span class='fa fa-calendar-check-o '
          | Этапы работы с нами
        div class='row left'
          div class='col-lg-6 '
            p
              i class='fa fa-check'
              | 1. Позвоните по одному из номеров и договоритесь с нашим дизайнером о встрече в комфортное для вас время.
          div class='col-lg-6 '
            p
              i class='fa fa-check'
              | 2. Позвоните по одному из номеров и договоритесь с нашим дизайнером о встрече в комфортное для вас время.
        div class='row left'
          div class='col-lg-6'
            p
              i class='fa fa-check'
              | 3. Наш дизайнер определит точные размеры для проектируемой мебели и обсудит с вами ее оформление, составит эскизы. После, мы рассчитаем примерную стоимость изделия.
          div class='col-lg-5'
            p
              i class='fa fa-check'
              | 4. Следующая стадия - производство заказа. Используя лучшее оборудования и материал,мы в кратчайшие сроки производим изделие.